# <font color="blue">编程任务7</font>

本次任务中需要事先安装numpy

1，        将[1,2,3]转化成numpy array

2，        打印数组中元素的数据类型

3，        打印numpy数组[[1,2,3],[4,5,6]]的shape

4，        打印3中数组维数

5，        将3中数组调整为1维数组

6，        生成一个1到12的数字序列，将这个序列改成3*4的数组

7，        生成一个3*5的数组全部初始化为0

8，        生成一个3*5的数组全部初始化为1

9，        生成一个跟3中相同维度的数组，全部初始化为0（zeros_like）

10，      数组堆叠。给定数组a

[[1,2],

[3,4]]

和数组b

[[5,6],

[7,8]]

生成数组的形式为

[[1,2,5,6],

[3,4,7,8]]

In [4]:
import numpy as np

# 1， 将[1,2,3]转化成numpy array
a1 = np.array([1, 2, 3])

In [5]:
# 2， 打印数组中元素的数据类型
print(a1.dtype)

int64


In [7]:
# 3， 打印numpy数组[[1,2,3],[4,5,6]]的shape
a3 = np.array([[1, 2, 3], [4, 5, 6]])
print(a3.shape)

(2, 3)


In [8]:
#4,打印3中数组维数
print(a3.ndim)

2


In [14]:
#5， 将3中数组调整为1维数组
a5 = np.ravel(a3)
print(a5)

[1 2 3 4 5 6]


In [16]:
#6， 生成一个1到12的数字序列，将这个序列改成3*4的数组
a6 = np.array(range(1, 13)).reshape(3, 4)
print(a6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#7， 生成一个3*5的数组全部初始化为0
a7 = np.zeros((3, 5))
print(a7)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [18]:
#8， 生成一个3*5的数组全部初始化为1
a8 = np.ones((3, 5))
print(a8)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [19]:
#9， 生成一个跟3中相同维度的数组，全部初始化为0（zeros_like）
a9 = np.zeros_like(a3)
print(a9)

[[0 0 0]
 [0 0 0]]


In [37]:
#10， 数组堆叠
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
a10 = np.array([[x, y] for x, y in  zip(a, b)]).reshape(2, 4)
print(a10)

[[1 2 5 6]
 [3 4 7 8]]
